# Generated by Django 2.2.2 on 2019-06-21 18:42

from django.db import migrations


'''
Method to populate the initial information needed for the system to work properly.
'''
def populate_initial(apps, schema_editor):
    Brand = apps.get_model('stock', 'Brand')
    brand = Brand(name='BOCH')
    brand.save()

    list_types = ['Antifreeze liquid', 'Oil', 'Battery', 'Fan','Water pump','Spark plug','AC filter','Air filter','Oil filter']
    Type = apps.get_model('stock', 'Type')
    for type_name in list_types:
        type = Type(name=type_name)
        type.save()

    list_categories = ['Hybrid','Electric','Gas','Diesel']
    Category = apps.get_model('stock', 'Category')
    for cat_name in list_categories:
        cat = Category(name=cat_name)
        cat.save()

    list_auto = ['Hybrid','Electric','Gas','Diesel']
    AutoCategory = apps.get_model('stock', 'AutoCategory')
    for auto_name in list_auto:
        auto = AutoCategory(name=auto_name)
        auto.save()

'''
On migrate this class runs the populate_initial methtod to create the initial information for
the models Brand, Type, Category, AutoCategory
'''
class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_shipment'),
    ]

    operations = [
        migrations.RunPython(populate_initial)
    ]
